# Puerto diferente para no chocar con Laboratorios
server.port=8082
spring.application.name=ms-usuarios

# --- CONFIGURACIÓN ORACLE LOCAL ---
spring.datasource.url=jdbc:oracle:thin:@host.docker.internal:1521/xe
spring.datasource.username=C##MAESTRO
spring.datasource.password=Duoc1234$$3210
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Config (Crea la tabla usuarios automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Logs para la rúbrica
logging.level.root=INFO
logging.level.com.usuario.user=DEBUG